import Link from "next/link";

import { requireAdmin } from "@/lib/auth";
import { getMicrosoftConfigurationProblem, hasOneDriveAuthorization } from "@/lib/onedrive";
import { getLearningSpaces } from "@/lib/repositories";

import { createLearningSpaceAction } from "../actions";

export const dynamic = "force-dynamic";

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ onedrive?: string }> }) {
  await requireAdmin();
  const [{ onedrive }, spaces, oneDriveAuthorized] = await Promise.all([searchParams, getLearningSpaces(), hasOneDriveAuthorization()]);
  const microsoftProblem = getMicrosoftConfigurationProblem();
  return <main className="page-shell narrow-page"><Link href="/admin" className="back-link">Terug naar beheer</Link><p className="eyebrow">Globaal beheer</p><h1>Leeromgevingen</h1><p>Elke leeromgeving heeft een eigen bron, synchronisatie, portfolio&apos;s, thema&apos;s en foutmeldingen. Bronbestanden blijven read-only.</p><section className="settings-section"><h2>OneDrive-verbinding</h2><p>{oneDriveAuthorized ? "OneDrive is app-breed verbonden. Drive- en map-ID's blijven per leeromgeving ingesteld." : "Verbind een Microsoft-account voordat je OneDrive-bronnen synchroniseert."}</p>{onedrive === "connected" ? <p className="success-message" role="status">OneDrive is verbonden.</p> : null}{onedrive === "authorization-failed" || onedrive === "connection-failed" ? <p className="form-message" role="alert">OneDrive verbinden is niet gelukt. Controleer de Microsoft-configuratie en probeer opnieuw.</p> : null}{microsoftProblem ? <p className="form-message" role="alert">{microsoftProblem}</p> : <Link className="secondary-button link-button" href="/api/onedrive/connect">{oneDriveAuthorized ? "OneDrive opnieuw verbinden" : "OneDrive verbinden"}</Link>}</section><div className="space-list">{spaces.map((space) => <div className="space-list-item" key={space.id}><div><strong>{space.name}</strong><span>/{space.slug} · {space.storageProvider === "local" ? (space.localSourcePath || "Bronmap nog instellen") : "OneDrive"}</span></div><Link className="secondary-button link-button" href={`/admin/${encodeURIComponent(space.slug)}/instellingen`}>Beheren</Link></div>)}</div><section className="settings-section"><h2>Leeromgeving toevoegen</h2><form action={createLearningSpaceAction} className="settings-form"><label>Naam<input name="name" required maxLength={100} placeholder="4de jaar" /></label><label>Publieke slug<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="4" /></label><label>Kort label<input name="shortLabel" required maxLength={20} placeholder="4" /></label><label>Sortering<input name="sortOrder" type="number" defaultValue={40} /></label><label>Bron<select name="storageProvider"><option value="local">Local filesystem</option><option value="onedrive">OneDrive</option></select></label><label>Lokale bronmap<input name="localSourcePath" placeholder="C:\\..." /></label><label>OneDrive drive-ID<input name="oneDriveDriveId" /></label><label>OneDrive map-ID<input name="oneDriveFolderId" /></label><label>OneDrive mapnaam of pad<input name="oneDriveFolderPath" /></label><button className="primary-button" type="submit">Leeromgeving toevoegen</button></form></section></main>;
}
